/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import view.CambiaPanel;
import view.PainelAtrasado;
import view.PainelCadastro2;
import view.PnlHome;
import view.PnlCadastro;
import view.PainelLiberar;
import view.PainellInfracao;
import view.PainelEmail;


/**
 *
 * @author henri
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
         setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.BtnHome.setSelected(true);
          URL caminhoIcone = getClass().getResource("/imagens/logo1.png");
         Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
         this.setIconImage(iconeTitulo);
        
        new CambiaPanel(pnPrincipal, new PnlHome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BtnAlunos = new rsbuttom.RSButtonMetro();
        BtnAnotacao = new rsbuttom.RSButtonMetro();
        BtnAtrasado = new rsbuttom.RSButtonMetro();
        BtnEmail = new rsbuttom.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();
        BtnHome = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnLiberar = new rsbuttom.RSButtonMetro();
        pnPrincipal = new javax.swing.JPanel();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cardápio-40.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 80));

        pnMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 366, -1));

        BtnAlunos.setBackground(new java.awt.Color(0, 0, 0));
        BtnAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-homem-estudante-40.png"))); // NOI18N
        BtnAlunos.setText("Dados dos alunos");
        BtnAlunos.setColorHover(new java.awt.Color(0, 0, 0));
        BtnAlunos.setColorNormal(new java.awt.Color(0, 0, 0));
        BtnAlunos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnAlunos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAlunos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnAlunos.setIconTextGap(25);
        BtnAlunos.setMargin(new java.awt.Insets(3, 14, 2, 14));
        BtnAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnAlunosMousePressed(evt);
            }
        });
        BtnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlunosActionPerformed(evt);
            }
        });
        pnMenu.add(BtnAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, 47));

        BtnAnotacao.setBackground(new java.awt.Color(0, 0, 0));
        BtnAnotacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-nota-40.png"))); // NOI18N
        BtnAnotacao.setText("Anotações");
        BtnAnotacao.setColorHover(new java.awt.Color(0, 0, 0));
        BtnAnotacao.setColorNormal(new java.awt.Color(0, 0, 0));
        BtnAnotacao.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnAnotacao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAnotacao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnAnotacao.setIconTextGap(25);
        BtnAnotacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnAnotacaoMousePressed(evt);
            }
        });
        BtnAnotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnotacaoActionPerformed(evt);
            }
        });
        pnMenu.add(BtnAnotacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, 47));

        BtnAtrasado.setBackground(new java.awt.Color(0, 0, 0));
        BtnAtrasado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel-40.png"))); // NOI18N
        BtnAtrasado.setText("Alunos atrasados");
        BtnAtrasado.setColorHover(new java.awt.Color(0, 0, 0));
        BtnAtrasado.setColorNormal(new java.awt.Color(0, 0, 0));
        BtnAtrasado.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnAtrasado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAtrasado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnAtrasado.setIconTextGap(25);
        BtnAtrasado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnAtrasadoMousePressed(evt);
            }
        });
        BtnAtrasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasadoActionPerformed(evt);
            }
        });
        pnMenu.add(BtnAtrasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 280, 47));

        BtnEmail.setBackground(new java.awt.Color(0, 0, 0));
        BtnEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-e-mail-40.png"))); // NOI18N
        BtnEmail.setText("Enviar e-mail");
        BtnEmail.setColorHover(new java.awt.Color(0, 0, 0));
        BtnEmail.setColorNormal(new java.awt.Color(0, 0, 0));
        BtnEmail.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnEmail.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnEmail.setIconTextGap(25);
        BtnEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnEmailMousePressed(evt);
            }
        });
        BtnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEmailActionPerformed(evt);
            }
        });
        pnMenu.add(BtnEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 280, 47));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        BtnHome.setBackground(new java.awt.Color(0, 0, 0));
        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-casa-40.png"))); // NOI18N
        BtnHome.setText("Tela inicial");
        BtnHome.setColorHover(new java.awt.Color(0, 0, 0));
        BtnHome.setColorNormal(new java.awt.Color(0, 0, 0));
        BtnHome.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnHome.setIconTextGap(25);
        BtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnHomeMousePressed(evt);
            }
        });
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnMenu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SERVIÇOS");
        pnMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/200 branca.png"))); // NOI18N
        pnMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 342, 170));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GERENCIAMENTO");
        pnMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 256, -1));

        BtnLiberar.setBackground(new java.awt.Color(0, 0, 0));
        BtnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-ok-40.png"))); // NOI18N
        BtnLiberar.setText("Liberações");
        BtnLiberar.setColorHover(new java.awt.Color(0, 0, 0));
        BtnLiberar.setColorNormal(new java.awt.Color(0, 0, 0));
        BtnLiberar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BtnLiberar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnLiberar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnLiberar.setIconTextGap(25);
        BtnLiberar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnLiberarMousePressed(evt);
            }
        });
        BtnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLiberarActionPerformed(evt);
            }
        });
        BtnLiberar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnLiberarKeyPressed(evt);
            }
        });
        pnMenu.add(BtnLiberar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 280, 47));

        jPanel1.add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 280, 1000));

        pnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnPrincipal.setMaximumSize(new java.awt.Dimension(1620, 950));
        pnPrincipal.setMinimumSize(new java.awt.Dimension(1620, 950));
        pnPrincipal.setPreferredSize(new java.awt.Dimension(1620, 950));
        pnPrincipal.setLayout(new javax.swing.BoxLayout(pnPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(pnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 1620, 950));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Tela Principal");

        setBounds(0, 0, 1920, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int posicao = this.pnMenu.getX();
        if(posicao> -1){
            Animacion.Animacion.mover_izquierda(0, -280, 2, 2, pnMenu);
        }else{
            Animacion.Animacion.mover_derecha(-280, 0, 2, 2, pnMenu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
 new CambiaPanel(pnPrincipal, new PnlHome());
        if (this.BtnHome.isSelected()){
    
    this.BtnHome.setColorNormal(new Color(51,51,51));
    this.BtnHome.setColorHover(new Color(51,51,51));
    this.BtnHome.setColorPressed(new Color(51,51,51));
    
    this.BtnAlunos.setColorNormal(new Color(0,0,0));
     this.BtnAlunos.setColorHover(new Color(51,51,51));
    this.BtnAlunos.setColorPressed(new Color(0,0,0));
    
    this.BtnAnotacao.setColorNormal(new Color(0,0,0));
     this.BtnAnotacao.setColorHover(new Color(51,51,51));
    this.BtnAnotacao.setColorPressed(new Color(0,0,0));
    
    this.BtnEmail.setColorNormal(new Color(0,0,0));
     this.BtnEmail.setColorHover(new Color(51,51,51));
    this.BtnEmail.setColorPressed(new Color(0,0,0));
    
   
    
    this.BtnAtrasado.setColorNormal(new Color(0,0,0));
     this.BtnAtrasado.setColorHover(new Color(51,51,51));
    this.BtnAtrasado.setColorPressed(new Color(0,0,0));
    
    this.BtnLiberar.setColorNormal(new Color(0,0,0));
    this.BtnLiberar.setColorHover(new Color(51,51,51));
    this.BtnLiberar.setColorPressed(new Color(0,0,0));
    
  
    
}else{
    
    this.BtnHome.setColorNormal(new Color(0,0,0));
     this.BtnHome.setColorHover(new Color(51,51,51));
    this.BtnHome.setColorPressed(new Color(0,0,0));
    

}
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlunosActionPerformed
  new CambiaPanel(pnPrincipal, new PainelCadastro2());
        if (this.BtnAlunos.isSelected()){
    
    this.BtnHome.setColorNormal(new Color(0,0,0));
    this.BtnHome.setColorHover(new Color(51,51,51));
    this.BtnHome.setColorPressed(new Color(0,0,0));
    
    this.BtnAlunos.setColorNormal(new Color(51,51,51));
     this.BtnAlunos.setColorHover(new Color(51,51,51));
    this.BtnAlunos.setColorPressed(new Color(51,51,51));
    
    this.BtnAnotacao.setColorNormal(new Color(0,0,0));
     this.BtnAnotacao.setColorHover(new Color(51,51,51));
    this.BtnAnotacao.setColorPressed(new Color(0,0,0));
    
    this.BtnEmail.setColorNormal(new Color(0,0,0));
     this.BtnEmail.setColorHover(new Color(51,51,51));
    this.BtnEmail.setColorPressed(new Color(0,0,0));
    
    
    this.BtnAtrasado.setColorNormal(new Color(0,0,0));
     this.BtnAtrasado.setColorHover(new Color(51,51,51));
    this.BtnAtrasado.setColorPressed(new Color(0,0,0));
    
    this.BtnLiberar.setColorNormal(new Color(0,0,0));
    this.BtnLiberar.setColorHover(new Color(51,51,51));
    this.BtnLiberar.setColorPressed(new Color(0,0,0));
    
    
}else{
    
    this.BtnAlunos.setColorNormal(new Color(0,0,0));
     this.BtnAlunos.setColorHover(new Color(51,51,51));
    this.BtnAlunos.setColorPressed(new Color(0,0,0));
    

}
    }//GEN-LAST:event_BtnAlunosActionPerformed

    private void BtnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeMousePressed
this.BtnHome.setSelected(true);
this.BtnAlunos.setSelected(false);
this.BtnAnotacao.setSelected(false);
this.BtnEmail.setSelected(false);
this.BtnAtrasado.setSelected(false);
this.BtnLiberar.setSelected(false);

    }//GEN-LAST:event_BtnHomeMousePressed

    private void BtnAlunosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAlunosMousePressed
 this.BtnHome.setSelected(false);
 this.BtnAlunos.setSelected(true);
 this.BtnAnotacao.setSelected(false);
this.BtnEmail.setSelected(false);
this.BtnAtrasado.setSelected(false);
this.BtnLiberar.setSelected(false);
    }//GEN-LAST:event_BtnAlunosMousePressed

    private void BtnAnotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnotacaoActionPerformed
new CambiaPanel(pnPrincipal, new PainellInfracao());
        if (this.BtnAnotacao.isSelected()){
    
   this.BtnHome.setColorNormal(new Color(0,0,0));
    this.BtnHome.setColorHover(new Color(51,51,51));
    this.BtnHome.setColorPressed(new Color(0,0,0));
    
    this.BtnLiberar.setColorNormal(new Color(0,0,0));
    this.BtnLiberar.setColorHover(new Color(51,51,51));
    this.BtnLiberar.setColorPressed(new Color(0,0,0));
    
    this.BtnAlunos.setColorNormal(new Color(0,0,0));
     this.BtnAlunos.setColorHover(new Color(51,51,51));
    this.BtnAlunos.setColorPressed(new Color(0,0,0));
    
    this.BtnAnotacao.setColorNormal(new Color(51,51,51));
     this.BtnAnotacao.setColorHover(new Color(51,51,51));
    this.BtnAnotacao.setColorPressed(new Color(51,51,51));
    
   this.BtnEmail.setColorNormal(new Color(0,0,0));
     this.BtnEmail.setColorHover(new Color(51,51,51));
    this.BtnEmail.setColorPressed(new Color(0,0,0));
    
    
    this.BtnAtrasado.setColorNormal(new Color(0,0,0));
     this.BtnAtrasado.setColorHover(new Color(51,51,51));
    this.BtnAtrasado.setColorPressed(new Color(0,0,0));
    
    
}else{
    
    this.BtnAnotacao.setColorNormal(new Color(0,0,0));
     this.BtnAnotacao.setColorHover(new Color(51,51,51));
    this.BtnAnotacao.setColorPressed(new Color(0,0,0));
    

}
    }//GEN-LAST:event_BtnAnotacaoActionPerformed

    private void BtnAnotacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAnotacaoMousePressed
this.BtnHome.setSelected(false);
 this.BtnAlunos.setSelected(false);
 this.BtnAnotacao.setSelected(true);
this.BtnEmail.setSelected(false);
this.BtnAtrasado.setSelected(false);
this.BtnLiberar.setSelected(false);
    }//GEN-LAST:event_BtnAnotacaoMousePressed

    private void BtnAtrasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasadoActionPerformed
       new CambiaPanel(pnPrincipal, new PainelAtrasado());
        if (this.BtnAtrasado.isSelected()){
    
   this.BtnHome.setColorNormal(new Color(0,0,0));
    this.BtnHome.setColorHover(new Color(51,51,51));
    this.BtnHome.setColorPressed(new Color(0,0,0));
    
     this.BtnLiberar.setColorNormal(new Color(0,0,0));
    this.BtnLiberar.setColorHover(new Color(51,51,51));
    this.BtnLiberar.setColorPressed(new Color(0,0,0));
    
    this.BtnAlunos.setColorNormal(new Color(0,0,0));
     this.BtnAlunos.setColorHover(new Color(51,51,51));
    this.BtnAlunos.setColorPressed(new Color(0,0,0));
    
    this.BtnAnotacao.setColorNormal(new Color(0,0,0));
     this.BtnAnotacao.setColorHover(new Color(51,51,51));
    this.BtnAnotacao.setColorPressed(new Color(0,0,0));
    
   this.BtnEmail.setColorNormal(new Color(0,0,0));
     this.BtnEmail.setColorHover(new Color(51,51,51));
    this.BtnEmail.setColorPressed(new Color(0,0,0));
    
    
    this.BtnAtrasado.setColorNormal(new Color(51,51,51));
     this.BtnAtrasado.setColorHover(new Color(51,51,51));
    this.BtnAtrasado.setColorPressed(new Color(51,51,51));
    
    
}else{
    
    this.BtnAtrasado.setColorNormal(new Color(0,0,0));
     this.BtnAtrasado.setColorHover(new Color(51,51,51));
    this.BtnAtrasado.setColorPressed(new Color(0,0,0));
    

}
    }//GEN-LAST:event_BtnAtrasadoActionPerformed

    private void BtnAtrasadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtrasadoMousePressed
this.BtnHome.setSelected(false);
 this.BtnAlunos.setSelected(false);
 this.BtnAnotacao.setSelected(false);
this.BtnEmail.setSelected(false);
this.BtnAtrasado.setSelected(true);
    }//GEN-LAST:event_BtnAtrasadoMousePressed

    private void BtnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmailActionPerformed
 new CambiaPanel(pnPrincipal, new PainelEmail());
        if (this.BtnEmail.isSelected()){
    
     this.BtnHome.setColorNormal(new Color(0,0,0));
    this.BtnHome.setColorHover(new Color(51,51,51));
    this.BtnHome.setColorPressed(new Color(0,0,0));
    
     this.BtnLiberar.setColorNormal(new Color(0,0,0));
    this.BtnLiberar.setColorHover(new Color(51,51,51));
    this.BtnLiberar.setColorPressed(new Color(0,0,0));
    
    this.BtnAlunos.setColorNormal(new Color(0,0,0));
     this.BtnAlunos.setColorHover(new Color(51,51,51));
    this.BtnAlunos.setColorPressed(new Color(0,0,0));
    
    this.BtnAnotacao.setColorNormal(new Color(0,0,0));
     this.BtnAnotacao.setColorHover(new Color(51,51,51));
    this.BtnAnotacao.setColorPressed(new Color(0,0,0));
    
    this.BtnEmail.setColorNormal(new Color(51,51,51));
     this.BtnEmail.setColorHover(new Color(51,51,51));
    this.BtnEmail.setColorPressed(new Color(51,51,51));
    
    
    this.BtnAtrasado.setColorNormal(new Color(0,0,0));
     this.BtnAtrasado.setColorHover(new Color(51,51,51));
    this.BtnAtrasado.setColorPressed(new Color(0,0,0));
    
}else{
    
    this.BtnEmail.setColorNormal(new Color(0,0,0));
     this.BtnEmail.setColorHover(new Color(51,51,51));
    this.BtnEmail.setColorPressed(new Color(0,0,0));
    

}
    }//GEN-LAST:event_BtnEmailActionPerformed

    private void BtnEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmailMousePressed
        this.BtnHome.setSelected(false);
 this.BtnAlunos.setSelected(false);
 this.BtnAnotacao.setSelected(false);
this.BtnEmail.setSelected(true);
this.BtnAtrasado.setSelected(false);
    }//GEN-LAST:event_BtnEmailMousePressed

    private void BtnLiberarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLiberarMousePressed
         this.BtnHome.setSelected(false);
 this.BtnAlunos.setSelected(false);
 this.BtnAnotacao.setSelected(false);
this.BtnEmail.setSelected(false);
this.BtnAtrasado.setSelected(false);
this.BtnLiberar.setSelected(true);
    }//GEN-LAST:event_BtnLiberarMousePressed

    private void BtnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLiberarActionPerformed
        new CambiaPanel(pnPrincipal, new PainelLiberar());
        if (this.BtnLiberar.isSelected()){
    
     this.BtnHome.setColorNormal(new Color(0,0,0));
    this.BtnHome.setColorHover(new Color(51,51,51));
    this.BtnHome.setColorPressed(new Color(0,0,0));
    
    this.BtnAlunos.setColorNormal(new Color(0,0,0));
     this.BtnAlunos.setColorHover(new Color(51,51,51));
    this.BtnAlunos.setColorPressed(new Color(0,0,0));
    
    this.BtnAnotacao.setColorNormal(new Color(0,0,0));
     this.BtnAnotacao.setColorHover(new Color(51,51,51));
    this.BtnAnotacao.setColorPressed(new Color(0,0,0));
    
    this.BtnEmail.setColorNormal(new Color(0,0,0));
     this.BtnEmail.setColorHover(new Color(51,51,51));
    this.BtnEmail.setColorPressed(new Color(0,0,0));
    
    this.BtnLiberar.setColorNormal(new Color(51,51,51));
     this.BtnLiberar.setColorHover(new Color(51,51,51));
    this.BtnLiberar.setColorPressed(new Color(51,51,51));
    
    
    this.BtnAtrasado.setColorNormal(new Color(0,0,0));
     this.BtnAtrasado.setColorHover(new Color(51,51,51));
    this.BtnAtrasado.setColorPressed(new Color(0,0,0));
    
}else{
    
    this.BtnLiberar.setColorNormal(new Color(0,0,0));
     this.BtnLiberar.setColorHover(new Color(51,51,51));
    this.BtnLiberar.setColorPressed(new Color(0,0,0));
    

}
        
    }//GEN-LAST:event_BtnLiberarActionPerformed

    private void BtnLiberarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnLiberarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLiberarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro BtnAlunos;
    private rsbuttom.RSButtonMetro BtnAnotacao;
    private rsbuttom.RSButtonMetro BtnAtrasado;
    private rsbuttom.RSButtonMetro BtnEmail;
    private rsbuttom.RSButtonMetro BtnHome;
    private rsbuttom.RSButtonMetro BtnLiberar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
